include: package:lints/recommended.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    unnecessary_this: true
    prefer_expression_function_bodies: false
    require_trailing_commas: true
