name: youtube_integration
publish_to: 'https://pub.dev'
description: >
  A Dart package that provides an easy-to-use interface for accessing the
  YouTube Data API. Fetch videos, playlists, channel details, comments, and more
  with minimal setup.

version: 1.0.0

repository: https://github.com/YousefMohamed6/youtube_integration
issue_tracker: https://github.com/YousefMohamed6/youtube_integration/issues
homepage: https://github.com/YousefMohamed6/youtube_integration

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build_runner: ^2.4.15
  dio: ^5.8.0+1
  flutter_gherkin: ^2.0.0
  http: ^1.3.0
  mockito: ^5.4.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - youtube
  - api
  - video
  - dart
  - integration

platforms:
  ? android
  ? ios
  ? web
  ? macos
  ? windows
  ? linux

license: MIT
