name: youtube_integration
description: >
  A Dart package that provides an easy-to-use interface for accessing the
  YouTube Data API. Fetch videos, playlists, channel details, comments, and more
  with minimal setup.

version: 1.0.2

repository: https://github.com/YousefMohamed6/youtube_integration
issue_tracker: https://github.com/YousefMohamed6/youtube_integration/issues
homepage: https://github.com/YousefMohamed6/youtube_integration

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  build_runner: ^2.4.13
  dio: ^5.8.0+1
  mockito: ^5.4.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - youtube
  - api
  - video
  - dart
  - integration

platforms:
  ? android
  ? ios
  ? web
  ? macos
  ? windows
  ? linux

license: MIT
